"""NTSB probable cause -> ICAO CICTT category (the harmonisation step).

CADORS rows arrive with a CICTT category but no text; NTSB rows have text but
no category. This trains a text classifier so both countries can be compared
on the same taxonomy.

Labels (in order of preference):
  1. data/labelled_seed.xlsx          human-reviewed labels, if it exists
  2. data/labelling_sheet_drafted.xlsx  gpt-4.1-mini labels (draft_code), unreviewed
The source used is recorded in docs/model-metrics.md. With (2), scores measure
how well this small model reproduces the LLM's labels, not accuracy against
ground truth.

Model: TF-IDF (1-2 grams, min_df=2, max 20,000 features) on probable cause +
findings -> LogisticRegression(class_weight='balanced'). Categories with fewer
than MIN_EXAMPLES labels are too rare to learn and are left out (reported).
Stratified 80/20 split for the scores, then refit on all labels for prediction.

    python ai/classify.py            # train, evaluate, predict, write to SQL
    python ai/classify.py --no-write # train and evaluate only
"""
import argparse
import pickle

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline

from aicommon import ROOT
from db import get_connection

MIN_EXAMPLES = 5
SEED = 42
REVIEWED = ROOT / "data" / "labelled_seed.xlsx"
DRAFTED = ROOT / "data" / "labelling_sheet_drafted.xlsx"
MODEL = ROOT / "ai" / "model.pkl"
METRICS = ROOT / "docs" / "model-metrics.md"


def features(cause, findings) -> pd.Series:
    return pd.Series(cause).fillna("").astype(str) + " || " + pd.Series(findings).fillna("").astype(str)


def load_labels():
    if REVIEWED.exists():
        d = pd.read_excel(REVIEWED, sheet_name="Label")
        d["label"] = d["cictt_code"]
        source = "human-reviewed (data/labelled_seed.xlsx)"
        agreement = (d["draft_code"] == d["cictt_code"]).mean() if "draft_code" in d else None
    else:
        d = pd.read_excel(DRAFTED, sheet_name="Label")
        d["label"] = d["draft_code"]
        source = "gpt-4.1-mini drafts, NOT reviewed by a person (data/labelling_sheet_drafted.xlsx)"
        agreement = None
    d = d[d["label"].notna()].copy()
    d["label"] = d["label"].astype(str).str.strip().str.upper()
    return d, source, agreement


def pipeline():
    return make_pipeline(
        TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_features=20000, sublinear_tf=True),
        LogisticRegression(class_weight="balanced", max_iter=1000, random_state=SEED))


def train(d):
    counts = d["label"].value_counts()
    keep = counts[counts >= MIN_EXAMPLES].index
    rare = counts[counts < MIN_EXAMPLES]
    t = d[d["label"].isin(keep)]
    X = features(t["probable_cause"], t["findings"])
    Xtr, Xte, ytr, yte = train_test_split(X, t["label"], test_size=0.2, stratify=t["label"], random_state=SEED)
    m = pipeline().fit(Xtr, ytr)
    pred = m.predict(Xte)
    scores = {
        "macro_f1": f1_score(yte, pred, average="macro"),
        "weighted_f1": f1_score(yte, pred, average="weighted"),
        "accuracy": float((pred == yte).mean()),
        "baseline_accuracy": float((yte == ytr.value_counts().idxmax()).mean()),
        "report": classification_report(yte, pred, zero_division=0),
        "n_train": len(ytr), "n_test": len(yte),
    }
    final = pipeline().fit(X, t["label"])          # refit on every usable label
    return final, scores, counts, rare


def write_metrics(scores, counts, rare, source, agreement, n_pred=None):
    lines = [
        "# Category classifier metrics", "",
        "Generated by `ai/classify.py`. Maps NTSB probable-cause text to ICAO CICTT",
        "occurrence categories so US and Canadian occurrences share one taxonomy.", "",
        f"- **Label source:** {source}",
        f"- **Labelled rows:** {int(counts.sum())} (NTSB corpus, July 2022 - Dec 2024, stratified by findings)",
        f"- **Model:** TF-IDF (1-2 grams) + logistic regression, class_weight=balanced",
        f"- **Split:** stratified 80/20 ({scores['n_train']} train / {scores['n_test']} test), seed {SEED}",
        f"- **Macro F1:** {scores['macro_f1']:.3f}",
        f"- **Weighted F1:** {scores['weighted_f1']:.3f}",
        f"- **Accuracy:** {scores['accuracy']:.3f} (always guessing the most common category: {scores['baseline_accuracy']:.3f})",
    ]
    if agreement is not None:
        lines.append(f"- **LLM draft agreement with human review:** {agreement:.1%}")
    else:
        lines += ["", "Because the labels come from an LLM and were not reviewed, these scores measure how",
                  "closely the small model reproduces gpt-4.1-mini's labels, not accuracy against ground",
                  "truth. Macro F1 on a 60-row test set is also noisy (a few rows swing it by several points)."]
    lines += ["", f"Categories with fewer than {MIN_EXAMPLES} labels were left out as too rare to learn: "
              + (", ".join(f"{c} ({n})" for c, n in rare.items()) or "none") + ".",
              "Occurrences of those kinds are assigned the nearest learned category, so rare categories",
              "are under-counted for NTSB.", ""]
    if n_pred is not None:
        lines += [f"Predictions written for {n_pred:,} NTSB occurrences with text, stored with",
                  "category_source = 'model' and the predicted probability in category_confidence.", ""]
    lines += ["## Per-category scores (test set)", "", "```", scores["report"].rstrip(), "```", ""]
    METRICS.write_text("\n".join(lines))


def predict_and_write(model, conn):
    cur = conn.cursor()
    cur.execute("SELECT f.occurrence_key, f.source_text, f.findings FROM fact_occurrence f "
                "JOIN dim_source_authority a ON a.authority_key = f.authority_key "
                "WHERE a.name = 'NTSB' AND f.source_text IS NOT NULL AND LEN(f.source_text) > 0")
    d = pd.DataFrame(cur.fetchall(), columns=["occurrence_key", "cause", "findings"])
    proba = model.predict_proba(features(d["cause"].tolist(), d["findings"].tolist()))
    d["code"] = model.classes_[proba.argmax(axis=1)]
    d["confidence"] = proba.max(axis=1)
    cur.execute("SELECT cictt_code, category_key FROM dim_category")
    keys = dict(cur.fetchall())
    missing = set(d["code"]) - set(keys)
    assert not missing, f"codes not in dim_category: {missing}"
    d["category_key"] = d["code"].map(keys)

    cur.execute("UPDATE fact_occurrence SET category_key = NULL, category_confidence = NULL, "
                "category_source = NULL WHERE category_source = 'model'")
    for i in range(0, len(d), 1000):
        c = d.iloc[i:i + 1000]
        v = ",\n".join(f"({int(k)}, {int(ck)}, {conf:.4f})"
                       for k, ck, conf in zip(c["occurrence_key"], c["category_key"], c["confidence"]))
        cur.execute("UPDATE f SET category_key = v.c, category_confidence = v.p, category_source = 'model'\n"
                    f"FROM fact_occurrence f\nJOIN (VALUES\n{v}\n) AS v(k, c, p) ON f.occurrence_key = v.k")
    conn.commit()
    return d


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--no-write", action="store_true")
    a = p.parse_args()

    d, source, agreement = load_labels()
    print(f"labels: {len(d)} rows, source: {source}")
    model, scores, counts, rare = train(d)
    print(f"macro F1 {scores['macro_f1']:.3f} | weighted F1 {scores['weighted_f1']:.3f} | "
          f"accuracy {scores['accuracy']:.3f} (majority-class baseline {scores['baseline_accuracy']:.3f})")
    print(f"learned {len(model.classes_)} categories; too rare to learn: " + (", ".join(f"{c} ({n})" for c, n in rare.items()) or "none"))
    with open(MODEL, "wb") as f:
        pickle.dump(model, f)
    if a.no_write:
        write_metrics(scores, counts, rare, source, agreement)
        print(f"wrote {MODEL.relative_to(ROOT)} and {METRICS.relative_to(ROOT)} (no database writes)")
        return
    conn = get_connection()
    pred = predict_and_write(model, conn)
    write_metrics(scores, counts, rare, source, agreement, len(pred))
    print(f"predicted {len(pred):,} NTSB occurrences; median confidence {pred['confidence'].median():.2f}")
    print("top predicted categories: " + ", ".join(f"{c} {n}" for c, n in pred["code"].value_counts().head(8).items()))
    print(f"wrote {MODEL.relative_to(ROOT)} and {METRICS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
